# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#   Copy seeds are in

Club.create( :name => "Ballyogan Celtic",
              :league_id => 3,
              :achievements => 'Winners 2012',
              :played => 15,
              :won => 10,
              :drawn => 1,
              :lost => 4,
              :goals_for => 41,
              :goals_against => 18,
)
Club.create(:name => "St Josephs Boys",
            :league_id => 3,
            :achievements => '2nd in the League',
            :played =>13,
            :won => 7,
            :drawn => 3,
            :lost => 3,
            :goals_for => 34,
            :goals_against => 15,
)
Club.create(:name => "Cabinteely Fc",
            :league_id => 3,
            :achievements => '2nd in the League',
            :played => 16,
            :won => 9,
            :drawn => 0,
            :lost => 7,
            :goals_for => 49,
            :goals_against => 16,
)
Club.create( :name => "Broadford Rovers",
             :league_id => 3,
             :achievements => 'Winners 2010',
             :played => 15,
             :won => 10,
             :drawn => 4,
             :lost => 1,
             :goals_for => 41,
             :goals_against => 18,
)
Club.create(:name => "Wayside Celtic",
            :league_id => 3,
            :achievements => 'League 09',
            :played =>13,
            :won => 5,
            :drawn => 5,
            :lost => 3,
            :goals_for => 34,
            :goals_against => 15,
)
Club.create(:name => "Knocklyon FC",
            :league_id => 3,
            :achievements => '3rd in the League',
            :played => 16,
            :won => 10,
            :drawn => 2,
            :lost => 4,
            :goals_for => 49,
            :goals_against => 16,
)
Club.create(:name => "Mount Merrion",
            :league_id => 2,
            :achievements => 'League Winners 2012',
            :played => 15,
            :won => 5,
            :drawn => 4,
            :lost => 6,
            :goals_for => 30,
            :goals_against => 34,
)
Club.create(:name => "St Killians FC",
            :league_id => 2,
            :achievements => 'Sheild Title 2009',
            :played => 10,
            :won => 5,
            :drawn => 1,
            :lost => 4,
            :goals_for => 13,
            :goals_against => 28,
)
Club.create(:name => "Killester United",
            :league_id => 2,
            :achievements => 'League Winners 2012',
            :played => 15,
            :won => 5,
            :drawn => 8,
            :lost => 2,
            :goals_for => 30,
            :goals_against => 34,
)
Club.create(:name => "Tymon Celtic",
            :league_id => 2,
            :achievements => 'Sheild Title 2007',
            :played => 13,
            :won => 5,
            :drawn => 4,
            :lost => 4,
            :goals_for => 13,
            :goals_against => 28,
)
Club.create(:name => "Ballyogan Celtic",
            :league_id => 2,
            :achievements => 'Sheild Title 2012',
            :played => 15,
            :won => 8,
            :drawn => 4,
            :lost => 3,
            :goals_for => 13,
            :goals_against => 28,
)

Club.create(:name => "St. Pats Phoenix",
            :league_id => 0,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 10,
            :drawn => 5,
            :lost => 3,
            :goals_for => 54,
            :goals_against => 44,
)
Club.create(:name => "Tolka Terriers FC",
            :league_id => 0,
            :achievements => 'League Title 2009',
            :played => 18,
            :won => 13,
            :drawn => 2,
            :lost => 3,
            :goals_for => 54,
            :goals_against => 44,
)
Club.create(:name => "Finglas South FC",
            :league_id => 0,
            :achievements => 'Sheild Title 2008',
            :played => 18,
            :won => 12,
            :drawn => 3,
            :lost => 3,
            :goals_for => 54,
            :goals_against => 44,
)
Club.create(:name => "Villa Celtic",
            :league_id => 0,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 13,
            :drawn => 5,
            :lost => 0,
            :goals_for => 54,
            :goals_against => 44,
)
Club.create(:name => "Wyteleaf United",
            :league_id => 0,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 15,
            :drawn => 0,
            :lost => 3,
            :goals_for => 54,
            :goals_against => 44,
)
Club.create(:name => "Ballyogan Celtic",
            :league_id => 0,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 15,
            :drawn => 1,
            :lost => 2,
            :goals_for => 54,
            :goals_against => 44,
)
Club.create(:name => "O Casey Celtic",
            :league_id => 0,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 16,
            :drawn => 0,
            :lost => 2,
            :goals_for => 34,
            :goals_against => 65,
)
Club.create(:name => "Palmerstown FC",
            :league_id => 0,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 9,
            :drawn => 5,
            :lost => 4,
            :goals_for => 56,
            :goals_against => 23,
)
Club.create(:name => "Domnic Celtic",
            :league_id => 0,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 6,
            :drawn => 5,
            :lost => 7,
            :goals_for => 23,
            :goals_against => 44,
)
Club.create(:name => "Griffith Rovers",
            :league_id => 0,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 5,
            :drawn => 5,
            :lost => 8,
            :goals_for => 45,
            :goals_against => 56,
)

Club.create(:name => "Ballyogan Celtic",
            :league_id => 1,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 10,
            :drawn => 5,
            :lost => 3,
            :goals_for => 54,
            :goals_against => 44,
)
Club.create(:name => "Grange United",
            :league_id => 1,
            :achievements => 'League Title 2009',
            :played => 18,
            :won => 13,
            :drawn => 2,
            :lost => 3,
            :goals_for => 54,
            :goals_against => 44,
)
Club.create(:name => "Sheriff YC",
            :league_id => 1,
            :achievements => 'Sheild Title 2008',
            :played => 18,
            :won => 12,
            :drawn => 3,
            :lost => 3,
            :goals_for => 54,
            :goals_against => 44,
)
Club.create(:name => "Villa Celtic",
            :league_id => 1,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 13,
            :drawn => 5,
            :lost => 0,
            :goals_for => 54,
            :goals_against => 44,
)
Club.create(:name => "Brookfield Celtic",
            :league_id => 1,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 15,
            :drawn => 0,
            :lost => 3,
            :goals_for => 54,
            :goals_against => 44,
)
Club.create(:name => "Markievecz ",
            :league_id => 1,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 15,
            :drawn => 1,
            :lost => 2,
            :goals_for => 54,
            :goals_against => 44,
)
Club.create(:name => "Shielton",
            :league_id => 1,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 16,
            :drawn => 0,
            :lost => 2,
            :goals_for => 34,
            :goals_against => 65,
)
Club.create(:name => "Palmerstown FC",
            :league_id => 1,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 9,
            :drawn => 5,
            :lost => 4,
            :goals_for => 56,
            :goals_against => 23,
)
Club.create(:name => "Kippure Park",
            :league_id => 1,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 6,
            :drawn => 5,
            :lost => 7,
            :goals_for => 23,
            :goals_against => 44,
)
Club.create(:name => "Marks Celtic",
            :league_id => 1,
            :achievements => 'Sheild Title 2009',
            :played => 18,
            :won => 5,
            :drawn => 5,
            :lost => 8,
            :goals_for => 45,
            :goals_against => 56,
)

