# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#   Copy seeds are in

Player.create(:team_id => 1,
              :first_name => 'Gerard',
              :last_name => 'Boland',
              :dob => '1996-05-19',
              :position => 'Goalkeeper',
              :squad_number => 1,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_goalkeeper.jpg",
              :phone => '08766645344',
              :email => 'ger@email.com',
)
Player.create(:team_id => 1,
              :first_name => 'Dale',
              :last_name => 'Winters',
              :dob => '1996-12-09',
              :position => 'Defender',
              :squad_number => 2,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_defender_1.jpg",
              :phone => '08666645344',
              :email => 'ger@email.com',
)

Player.create(:team_id => 1,
              :first_name => 'Greg',
              :last_name => 'Peters',
              :dob => '1996-01-19',
              :position => 'Defender',
              :squad_number => 3,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_defender_2.jpg",
              :phone => '08756645344',
              :email => 'greg@email.com',
)

Player.create(:team_id => 1,
              :first_name => 'Gerard',
              :last_name => 'Boland',
              :dob => '1996-05-19',
              :position => 'Central Defender',
              :squad_number => 4,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_defender_3.jpg",
              :phone => '08761645344',
              :email => 'ger@email.com',
)

Player.create(:team_id => 1,
              :first_name => 'Gerard',
              :last_name => 'Boland',
              :dob => '1996-05-19',
              :position => 'Central Defender',
              :squad_number => 5,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_defender_4.jpg",
              :phone => '08766145344',
              :email => 'ger@email.com',
)

Player.create(:team_id => 1,
              :first_name => 'Gerard',
              :last_name => 'Boland',
              :dob => '1996-05-19',
              :position => 'Midfield',
              :squad_number => 6,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_mid_1.jpg",
              :phone => '08766625344',
              :email => 'ger@email.com',
)

Player.create(:team_id => 1,
              :first_name => 'Gerard',
              :last_name => 'Boland',
              :dob => '1996-05-19',
              :position => 'Midfield',
              :squad_number => 7,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_mid_2.jpg",
              :phone => '08766649844',
              :email => 'ger@email.com',
)

Player.create(:team_id => 1,
              :first_name => 'Gerard',
              :last_name => 'Boland',
              :dob => '1996-05-19',
              :position => 'Centre Midfield',
              :squad_number => 8,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_mid_3.jpg",
              :phone => '08766645314',
              :email => 'ger@email.com',
)

Player.create(:team_id => 1,
              :first_name => 'Gerard',
              :last_name => 'Boland',
              :dob => '1996-05-19',
              :position => 'Centre Midfield',
              :squad_number => 9,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_mid_4.jpg",
              :phone => '08766645311',
              :email => 'ger@email.com',
)

Player.create(:team_id => 1,
              :first_name => 'Gerard',
              :last_name => 'Boland',
              :dob => '1996-05-19',
              :position => 'Centre Forward',
              :squad_number => 10,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_forward_1.jpg",
              :phone => '08754645314',
              :email => 'ger@email.com',
)

Player.create(:team_id => 1,
              :first_name => 'Gerard',
              :last_name => 'Boland',
              :dob => '1996-05-19',
              :position => 'Centre Forward',
              :squad_number => 11,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_forward_2.jpg",
              :phone => '08754105314',
              :email => 'ger@email.com',
)

Player.create(:team_id => 1,
              :first_name => 'Gerard',
              :last_name => 'Boland',
              :dob => '1996-05-19',
              :position => 'Centre Midfield',
              :squad_number => 14,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_mid_5.jpg",
              :phone => '08734105314',
              :email => 'ger@email.com',
)

Player.create(:team_id => 1,
              :first_name => 'Gerard',
              :last_name => 'Boland',
              :dob => '1996-05-19',
              :position => 'Central Defender',
              :squad_number => 15,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_defender_5.jpg",
              :phone => '08764105324',
              :email => 'ger@email.com',
)
Player.create(:team_id => 1,
              :first_name => 'Gerard',
              :last_name => 'Boland',
              :dob => '1996-05-19',
              :position => 'Central Defender',
              :squad_number => 16,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_defender_6.jpg",
              :phone => '08764105329',
              :email => 'ger@email.com',
)
Player.create(:team_id => 1,
              :first_name => 'Gerard',
              :last_name => 'Boland',
              :dob => '1996-05-19',
              :position => 'Centre Forward',
              :squad_number => 17,
              :description => "Height 6'2",
              :achievements => "League Winner 2011",
              :image_url => "17_forward_4.jpg",
              :phone => '08664105724',
              :email => 'ger@email.com',
)

